Update postBuild

diff --git a/.binder/postBuild b/.binder/postBuild
--- a/.binder/postBuild
+++ b/.binder/postBuild
@@ -4,20 +4,41 @@ set -e
 echo "Starting postBuild script..."
 
 # Ensure the .jupyter directory exists
-mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/shortcuts-extension
-if [ $? -eq 0 ]; then
-    echo "Created .jupyter directory successfully."
-else
-    echo "Failed to create .jupyter directory."
-fi
+#mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/shortcuts-extension
+
+
+mkdir -p /home/jovyan/src/
+
+mkdir -p /jovyan/local/etc/jupyter/lab/ # system wide configuration
+mkdir -p ~/.jupyter/lab/workspaces/ # workspaces
+mkdir -p ~/.jupyter/lab/settings/
+mkdir -p /jovyan/local/etc/jupyter/lab/settings/
+
+
+#if [ $? -eq 0 ]; then
+#    echo "Created .jupyter directory successfully."
+#else
+#    echo "Failed to create .jupyter directory."
+#fi
+
+
 
 # Copy the overrides.json file to the appropriate directory
-cp .binder/overrides.json ~/.jupyter/lab/user-settings/@jupyterlab/shortcuts-extension/overrides.json
-if [ $? -eq 0 ]; then
-    echo "Copied overrides.json successfully."
-else
-    echo "Failed to copy overrides.json."
-fi
+#cp .binder/overrides.json ~/.jupyter/lab/user-settings/@jupyterlab/shortcuts-extension/overrides.json
+
+cp .binder/overrides.json /home/jovyan/src/
+cp .binder/overrides.json /jovyan/local/etc/jupyter/lab/ # system wide configuration
+cp .binder/overrides.json ~/.jupyter/lab/workspaces/ # workspaces
+cp .binder/overrides.json ~/.jupyter/lab/settings/
+cp .binder/overrides.json /jovyan/local/etc/jupyter/lab/settings
+
+
+
+#if [ $? -eq 0 ]; then
+#    echo "Copied overrides.json successfully."
+#else
+   # echo "Failed to copy overrides.json."
+#fi
 
 # Final echo to indicate completion
 echo "postBuild script completed."
